[package]
name = "pm"
version = "0.1.0"
edition = "2024"

[dependencies]
op-ipc = { path = "op-ipc" }
enigo = "=0.3.0"
femtovg = { version = "0.26.0", default-features = false, features = ["textlayout"] }
glfw = { version = "0.62.0", default-features = false, features = ["raw-window-handle-v0-6"] }
livesplit-hotkey = { version = "0.8.1" }
raw-window-handle = "0.6.2"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = { version = "0.5.2", default-features = false }
objc2-foundation = { version = "0.2.2", features = ["NSThread"] }
objc2-app-kit = { version = "0.2.2", default-features = false, features = ["NSWindow", "NSView", "NSResponder", "NSPanel", "NSApplication", "NSRunningApplication"] }

[workspace]
members = ["dl", "op-ipc"]
